version: '3'
services:

  app:
    image: app:latest
    ports:
      - "8082:8082"

    networks:
      - communicate

  nginx:
    image: nginx:latest
    ports:
      - "8083:8083"

    networks:
      - communicate

networks:
  communicate:
    driver: overlay




 
